model:
  name: vae
  variant: L

  vae:
    patch_size: 8
    in_channels: 3

    latent_dim: 4

    attention_type: rope

    mlp_ratio: 4.0
    dropout: 0.0
    bias: true

loss:
  beta: 1.0e-6
  lpips_weight: 0.1
  reconstruction: mse

eval:
  every: 1000

  reconstruction:
    enabled: true
    num_images: 8

train:

  resume: null